language: python

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq python-numpy python-scipy

install:
    - pip install . --use-mirrors
    - pip install -r requirements.txt --use-mirrors
    - pip install coveralls --use-mirrors

script:
    - nosetests --with-coverage --cover-package=concert concert

after_success:
    - coveralls
